#!/usr/bin/env bash
set -e
set -u

if ! command -v gh &> /dev/null
then
    echo "gh command could not be found, please install it to use this script"
    exit
fi

git init
git add .
git commit -m "Initial commit"
repo_name="Linux_bin_utils"
gh repo create "Carltk/$repo_name" --public --source=. --remote=origin
